trigger:
  branches:
    include:
      - main


pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20' # or your preferred Node.js version
  - script: |
      npm install
      npm test
    displayName: 'Install dependencies and run tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop
